export const GET_ARTICLES = 'GET_ARTICLES';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const IS_LOADING = 'IS_LOADING';
export const SET_ARTICLES_PER_PAGE = 'SET_ARTICLES_PER_PAGE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const HANDLE_ARTICLE_CLICK = 'HANDLE_ARTICLE_CLICK';
export const ADD_PASS = 'ADD_PASS';
export const EDIT_TOPIC = 'EDIT_TOPIC';